### PR TITLE
added a Blackjack game which I made using Python

### PR DESCRIPTION
**Pull request by Rudra50000**
I am Rudraneel Mandal and I created a Blaackjack game using Python.

### CODE REVIEW

**Comment by Rudra50000** [comment]
> I am Rudraneel Mandal and I created a Blaackjack game using Python.

Sorry accidentally typed Blaackjack instead of Blackjack.

**Comment by Rudra50000** [comment]
Sorry some glitch happened and the files are empty.

**Comment by Rudra50000** [comment]
I am resending the files

**Comment by Rudra50000** [comment]
Now the files are there.

**Comment by kizule** [comment]
No problem, this looks very cool! 😄

**Comment by Rudra50000** [comment]
> No problem, this looks very cool! 😄

Thanks! :D

**Pull request merged**
