### PR TITLE
added a Password Generator which I made using Python

### PR DESCRIPTION
**Pull request by Rudra50000**
Hi! I am Rudraneel Mandal and I created a Password Generator using Python.

### CODE REVIEW

**Comment by kizule** [comment]
Hi, this looks cool. Good luck in participating in Hacktoberfest! 😄

**Comment by kizule** [comment]
Be free to add yourself in CONTRIBUTORS.md.

**Comment by Rudra50000** [comment]
> Hi, this looks cool. Good luck in participating in Hacktoberfest! 😄

Can you please tell me how I can add myself in Contributors.md? I am new.

**Comment by kizule** [comment]
> 
> 
> > Hi, this looks cool. Good luck in participating in Hacktoberfest! 😄
> 
> Can you please tell me how I can add myself in Contributors.md? I am new.

You did it already. Good job. 👍

**Comment by Rudra50000** [comment]
> > > Hi, this looks cool. Good luck in participating in Hacktoberfest! 😄
> > 
> > 
> > Can you please tell me how I can add myself in Contributors.md? I am new.
> 
> You did it already. Good job. 👍

Thanks! :D

**Pull request merged**
